openapi: 3.0.0
info:
  title: Device and Microservice Statistics API
  version: 1.0.0
  description: API for retrieving device statistics and microservice usage information

servers:
  - url: https://{tenant}.cumulocity.com/service/metrics-aggregator
    variables:
      tenant:
        default: mytenant
        description: The tenant identifier

paths:
  /devices/{type}/{date}:
    get:
      summary: Get device statistics
      description: Retrieve device statistics for a specific type and date
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
          description: The type of devices to query
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
          example: "2024-09-01"
          description: The date to query statistics for (YYYY-MM-DD)
        - name: includeSubtenants
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: Whether to include subtenant information in the response
        - name: useTenantDeviceClasses
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: Whether to use tenant-specific device classes instead of global ones
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalMeas:
                    type: integer
                  totalDeviceCount:
                    type: integer
                  totalDeviceClasses:
                    type: array
                    items:
                      $ref: "#/components/schemas/DeviceClass"
                  tenantAggregation:
                    type: object
                    additionalProperties:
                      $ref: "#/components/schemas/TenantStats"

  /microservices/:
    get:
      summary: Get microservice usage statistics
      description: Retrieve microservice usage statistics for a specific date range
      parameters:
        - name: dateFrom
          in: query
          required: true
          schema:
            type: string
            format: date
          example: "2024-08-01"
          description: Start date of the period (YYYY-MM-DD)
        - name: dateTo
          in: query
          required: true
          schema:
            type: string
            format: date
          example: "2024-09-01"
          description: End date of the period (YYYY-MM-DD)
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalUsage:
                    $ref: "#/components/schemas/UsageStats"
                  subTenantStat:
                    type: object
                    additionalProperties:
                      $ref: "#/components/schemas/SubTenantUsage"

components:
  schemas:
    DeviceClass:
      type: object
      properties:
        className:
          type: string
        avgMinMea:
          type: number
        avgMaxMea:
          type: string
        monthlyThreshold:
          type: integer
        count:
          type: integer

    TenantStats:
      type: object
      properties:
        meas:
          type: integer
        devicesCount:
          type: integer
        deviceClasses:
          type: array
          items:
            $ref: "#/components/schemas/DeviceClass"

    UsageStats:
      type: object
      properties:
        memory:
          type: integer
        cpu:
          type: integer
        usedBy:
          type: array
          items:
            $ref: "#/components/schemas/ServiceUsage"

    ServiceUsage:
      type: object
      properties:
        memory:
          type: integer
        name:
          type: string
        cpu:
          type: integer
        cause:
          type: string

    SubTenantUsage:
      type: object
      properties:
        memory:
          type: integer
        cpu:
          type: integer
        usedBy:
          type: array
          items:
            $ref: "#/components/schemas/ServiceUsage"
