name: Docker Release Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Adjust this to your Java version
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./metrics-aggregator
      env:
        C8Y_BOOTSTRAP_TENANT: ${{ secrets.C8Y_BOOTSTRAP_TENANT }}
        C8Y_BASE_URL: ${{ secrets.C8Y_BASE_URL }}
        C8Y_BOOTSTRAP_USER: ${{ secrets.C8Y_BOOTSTRAP_USER }}
        C8Y_BOOTSTRAP_PASSWORD: ${{ secrets.C8Y_BOOTSTRAP_PASSWORD }}
      run: mvn package
        -DC8Y.bootstrap.tenant="${C8Y_BOOTSTRAP_TENANT}"
        -DC8Y.baseURL="${C8Y_BASE_URL}"
        -DC8Y.bootstrap.user="${C8Y_BOOTSTRAP_USER}"
        -DC8Y.bootstrap.password="${C8Y_BOOTSTRAP_PASSWORD}"
